[package]
name = "tata"
version = "0.1.0"
authors = ["Dirgaaa <dirgayuditama6@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6"
ratcn = { version = "0.0.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web-time = "1.1"
fastrand = "2.5"
strum = { version = "0.28", features = ["derive"] }
unicode-width = "0.2"
time = { version = "0.3", features = ["formatting", "serde", "wasm-bindgen"] }
catppuccin = "2.8"
logos = "0.16"
tachyonfx = "0.25"
fuzzy-matcher = "0.3"
tui-big-text = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ratatui = { version = "0.30", default-features = false, features = ["layout-cache", "std"] }
ratzilla = "0.3"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Window", "Storage", "AudioContext", "OscillatorNode", "GainNode"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ratatui = { version = "0.30", default-features = false, features = ["layout-cache", "std", "crossterm"] }
crossterm = { version = "0.29", features = ["event-stream"] }
dirs = "7"
